package COP4331;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Brownie
 */
public class CategoryCard extends javax.swing.JPanel 
{

    /**
     * Creates new form categoryCard
     */
    public CategoryCard() 
    {
        initComponents();
    }

    
    public CategoryCard generateLayout(String category, int count, ImageIcon image)
    {
        System.out.println("Generating product layout");
        imageLabel.setText("");
        imageLabel.setHorizontalAlignment(JLabel.CENTER);
        imageLabel.setIcon(image);

        categoryLabel.setText(category);

        numberLabel.setText(String.valueOf(count) + " items");
        
        return this;
    }
    
    public String getCategory()
    {
        return categoryLabel.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        categoryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoryLabel.setText("[Category]");

        numberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numberLabel.setText("[Number of items]");

        imageLabel.setText("[image]");
        imageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numberLabel)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel numberLabel;
    // End of variables declaration//GEN-END:variables
}
